# Generated by Django 5.2.6 on 2025-10-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('phone_model', models.CharField(choices=[('iPhone', 'iPhone'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('Other', 'Other')], max_length=50, verbose_name='Модель телефона')),
                ('service', models.CharField(choices=[('screen', 'Экран'), ('case', 'Корпус'), ('kit', 'Комплект'), ('repair', 'Ремонт')], max_length=20, verbose_name='Услуга')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
